# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: "2.4"

networks:
  PropertyBecho:
    name: PropertyBecho

services:
  ca_landowner:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-landowner
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=4400
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:14400
    ports:
      - "4400:4400"
      - "14400:14400"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/landowner:/etc/hyperledger/fabric-ca-server
    container_name: ca_landowner
    networks:
      - PropertyBecho

  ca_landbuyer:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-landbuyer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=5500
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:15500
    ports:
      - "5500:5500"
      - "15500:15500"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/landbuyer:/etc/hyperledger/fabric-ca-server
    container_name: ca_landbuyer
    networks:
      - PropertyBecho

  ca_blockgaurdians:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-blockgaurdians
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=6600
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:16600
    ports:
      - "6600:6600"
      - "16600:16600"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/blockgaurdians:/etc/hyperledger/fabric-ca-server
    container_name: ca_blockgaurdians
    networks:
      - PropertyBecho

  ca_insurance:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-insurance
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7700
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17700
    ports:
      - "7700:7700"
      - "17700:17700"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/insurance:/etc/hyperledger/fabric-ca-server
    container_name: ca_insurance
    networks:
      - PropertyBecho

  ca_government:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-government
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8800
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:18800
    ports:
      - "8800:8800"
      - "18800:18800"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/government:/etc/hyperledger/fabric-ca-server
    container_name: ca_government
    networks:
      - PropertyBecho

  ca_orderer1:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-orderer1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=2200
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:12200
    ports:
      - "2200:2200"
      - "12200:12200"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/orderer1:/etc/hyperledger/fabric-ca-server
    container_name: ca_orderer1
    networks:
      - PropertyBecho
  ca_orderer2:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-orderer2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=2201
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:12201
    ports:
      - "2201:2201"
      - "12201:12201"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/orderer2:/etc/hyperledger/fabric-ca-server
    container_name: ca_orderer2
    networks:
      - PropertyBecho
  ca_orderer3:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-orderer3
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=2202
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:12202
    ports:
      - "2202:2202"
      - "12202:12202"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/orderer3:/etc/hyperledger/fabric-ca-server
    container_name: ca_orderer3
    networks:
      - PropertyBecho

 

